name: CI build checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cargo b -r
